export const SET_METATYPE_PRIORITY = 'SET_METATYPE_PRIORITY';
export const SET_MAGIC_OR_RESONANCE_PRIORITY = 'SET_MAGIC_OR_RESONANCE_PRIORITY'; 
export const SET_ATTRIBUTE_PRIORITY ='SET_ATTRIBUTE_PRIORITY'; 
export const SET_RESOURCES_PRIORITY = 'SET_RESOURCES_PRIORITY'; 
export const SET_SKILLS_PRIORITY = 'SET_SKILLS_PRIORITY';
export const SAVE_PRIORITIES = 'SAVE_PRIORITIES';
export const ERROR_NOT_ALL_PRIORITIES_PRESENT = 'ERROR_NOT_ALL_PRIORITIES_PRESENT';
