export const MODIFY_SKILL = 'MODIFY_SKILL';
export const MODIFY_BONUS_SKILL = 'MODIFY_BONUS_SKILL';
export const MODIFY_SKILL_GROUP = 'MODIFY_SKILL_GROUP';
export const FILTER_SKILL = 'FILTER_SKILL';
export const ADD_SKILL_SPECIALIZATION = 'ADD_SKILL_SPECIALIZATION';
export const REMOVE_SKILL_SPECIALIZATION = 'REMOVE_SKILL_SPECIALIZATION';