export const spells = {
			combat: [
		{
			spellCategory: 'combat',
			isElemental: true,
			isDirect: false,
			name: 'Acid Stream',
			isLOS: true,
			isArea: false,
			isMana: false,
			isPhysicalDamage: true,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: true,
			isDirect: false,
			name: 'Toxic Wave',
			isLOS: true,
			isArea: true,
			isMana: false,
			isPhysicalDamage: true,
			drain: -1,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: false,
			name: 'Punch',
			isLOS: false,
			isArea: false,
			isMana: false,
			isPhysicalDamage: false,
			drain: -6,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: false,
			name: 'Clout',
			isLOS: true,
			isArea: false,
			isMana: false,
			isPhysicalDamage: false,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: false,
			name: 'Blast',
			isLOS: true,
			isArea: true,
			isMana: false,
			isPhysicalDamage: false,
			drain: 0,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'DeathTouch',
			isLOS: false,
			isArea: false,
			isMana: true,
			isPhysicalDamage: true,
			drain: -6,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Manabolt',
			isLOS: true,
			isArea: false,
			isMana: true,
			isPhysicalDamage: true,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Manaball',
			isLOS: true,
			isArea: true,
			isMana: true,
			isPhysicalDamage: true,
			drain: 0,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: true,
			isDirect: false,
			name: 'Flamethrower',
			isLOS: true,
			isArea: false,
			isMana: false,
			isPhysicalDamage: true,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: true,
			isDirect: false,
			name: 'Fireball',
			isLOS: true,
			isArea: true,
			isMana: false,
			isPhysicalDamage: true,
			drain: -1,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: true,
			isDirect: false,
			name: 'Lightning Bolt',
			isLOS: true,
			isArea: false,
			isMana: false,
			isPhysicalDamage: true,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: true,
			isDirect: false,
			name: 'Ball Lightning',
			isLOS: true,
			isArea: true,
			isMana: false,
			isPhysicalDamage: true,
			drain: -1,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Shatter',
			isLOS: false,
			isArea: false,
			isMana: false,
			isPhysicalDamage: true,
			drain: -6,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Powerbolt',
			isLOS: true,
			isArea: false,
			isMana: false,
			isPhysicalDamage: true,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Powerball',
			isLOS: true,
			isArea: true,
			isMana: false,
			isPhysicalDamage: true,
			drain: 0,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Knockout',
			isLOS: false,
			isArea: false,
			isMana: true,
			isPhysicalDamage: false,
			drain: -6,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Stunbolt',
			isLOS: true,
			isArea: false,
			isMana: true,
			isPhysicalDamage: false,
			drain: -3,
			duration: 'I'
		},
		{
			spellCategory: 'combat',
			isElemental: false,
			isDirect: true,
			name: 'Stunball',
			isLOS: true,
			isArea: true,
			isMana: true,
			isPhysicalDamage: false,
			drain: 0,
			duration: 'I'
		}
	],
	detection: [
		{
			spellCategory: 'detection',
			name: 'Analyze Device',
			isActive: true,
			isDirectional: true,
			isMana: false,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'detection',
			name: 'Analyze Magic',
			isActive: true,
			isDirectional: true,
			isMana: false,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'detection',
			name: 'Analyze Truth',
			isActive: true,
			isDirectional: true,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'detection',
			name: 'Clairaudience',
			isActive: false,
			isDirectional: true,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'detection',
			name: 'Clairvoyance',
			isActive: false,
			isDirectional: true,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'detection',
			name: 'Combat Sense',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: true,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'detection',
			name: 'Detect Enemies',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: true,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'detection',
			name: 'Detect Enemies, Extended',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: true,
			isPsychic: false,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'detection',
			name: 'Detect Individual',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: true,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'detection',
			name: 'Detect Life',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: true,
			isPsychic: false,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'detection',
			name: 'Detect [Life Form]',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: true,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'detection',
			name: 'Detect [Life Form], Extended',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: true,
			isPsychic: false,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'detection',
			name: 'Detect Magic',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: true,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'detection',
			name: 'Detect Magic, Extended',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: true,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'detection',
			name: 'Detect [Object]',
			isActive: true,
			isDirectional: false,
			isMana: false,
			isLOS: false,
			isArea: true,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'detection',
			name: 'Mindlink',
			isActive: true,
			isDirectional: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: true,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'detection',
			name: 'Mind Probe',
			isActive: true,
			isDirectional: true,
			isMana: true,
			isLOS: false,
			isArea: false,
			isExtendedArea: false,
			isPsychic: false,
			duration: 'S',
			drain: 0
		}
	],
	health: [
		{
			spellCategory: 'health',
			name: 'Antidote',
			isEssence: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'P',
			drain: -3
		},
		{
			spellCategory: 'health',
			name: 'Cure Disease',
			isEssence: true,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'P',
			drain: -4
		},
		{
			spellCategory: 'health',
			name: 'Decrease [Attribute]',
			isEssence: true,
			isMana: false,
			isLOS: false,
			isArea: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'health',
			name: 'Detox',
			isEssence: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'P',
			drain: -6
		},
		{
			spellCategory: 'health',
			name: 'Heal',
			isEssence: true,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'P',
			drain: -4
		},
		{
			spellCategory: 'health',
			name: 'Increase [Attribute]',
			isEssence: true,
			isMana: false,
			isLOS: false,
			isArea: false,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'health',
			name: 'Incrase Reflexes',
			isEssence: true,
			isMana: false,
			isLOS: false,
			isArea: false,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'health',
			name: 'Oxygenate',
			isEssence: false,
			isMana: false,
			isLOS: false,
			isArea: false,
			duration: 'S',
			drain: -5
		},
		{
			spellCategory: 'health',
			name: 'Prophylaxis',
			isEssence: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'S',
			drain: -4
		},
		{
			spellCategory: 'health',
			name: 'Resist Pain',
			isEssence: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'P',
			drain: -6
		},
		{
			spellCategory: 'health',
			name: 'Stabilize',
			isEssence: false,
			isMana: true,
			isLOS: false,
			isArea: false,
			duration: 'P',
			drain: -4
		}

	],
	illusion: [
		{
			spellCategory: 'illusion',
			name: 'Agony',
			isRealistic: true,
			isMultisense: false,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: -4
		},
		{
			spellCategory: 'illusion',
			name: 'Mass Agony',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'illusion',
			name: 'Bugs',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'illusion',
			name: 'Swarm',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'illusion',
			name: 'Confusion',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'illusion',
			name: 'Mass Confusion',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'illusion',
			name: 'Chaos',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'illusion',
			name: 'Chaotic World',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'illusion',
			name: 'Entertainment',
			isRealistic: false,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -3
		},
		{
			spellCategory: 'illusion',
			name: 'Trid Entertainment',
			isRealistic: false,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'illusion',
			name: 'Invisibility',
			isRealistic: true,
			isMultisense: false,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'illusion',
			name: 'Improved Invisibility',
			isRealistic: true,
			isMultisense: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'illusion',
			name: 'Mask',
			isRealistic: true,
			isMultisense: true,
			isLOS: false,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'illusion',
			name: 'Physical Mask',
			isRealistic: true,
			isMultisense: true,
			isLOS: false,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'illusion',
			name: 'Phantasm',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'illusion',
			name: 'Trid Phantasm',
			isRealistic: true,
			isMultisense: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: 0
		},
		{
			spellCategory: 'illusion',
			name: 'Hush',
			isRealistic: true,
			isMultisense: false,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'illusion',
			name: 'Silence',
			isRealistic: true,
			isMultisense: false,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'illusion',
			name: 'Stealth',
			isRealistic: true,
			isMultisense: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -2
		}
	],
	manipulation: [
		{
			spellCategory: 'manipulation',
			name: 'Armor',
			isPhysical: true,
			isMental: false,
			isEnvironmental: false,
			isDamaging: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'manipulation',
			name: 'Control Actions',
			isPhysical: false,
			isMental: true,
			isEnvironmental: false,
			isDamaging: false,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'manipulation',
			name: 'Mob Control',
			isPhysical: false,
			isMental: true,
			isEnvironmental: false,
			isDamaging: false,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: 1
		},
		{
			spellCategory: 'manipulation',
			name: 'Control Thoughts',
			isPhysical: false,
			isMental: true,
			isEnvironmental: false,
			isDamaging: false,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'S',
			drain: 1
		},
		{
			spellCategory: 'manipulation',
			name: 'Mob Mind',
			isPhysical: false,
			isMental: true,
			isEnvironmental: false,
			isDamaging: false,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: 1
		},
		{
			spellCategory: 'manipulation',
			name: 'fling',
			isPhysical: true,
			isMental: false,
			isEnvironmental: false,
			isDamaging: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'I',
			drain: -2
		},
		{
			spellCategory: 'manipulation',
			name: 'Ice Sheet',
			isPhysical: false,
			isMental: false,
			isEnvironmental: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'I',
			drain: 0
		},
		{
			spellCategory: 'manipulation',
			name: 'Ignite',
			isPhysical: true,
			isMental: false,
			isEnvironmental: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'P',
			drain: -1
		},
		{
			spellCategory: 'manipulation',
			name: 'Influence',
			isPhysical: false,
			isMental: true,
			isEnvironmental: false,
			isLOS: true,
			isArea: false,
			isMana: true,
			duration: 'P',
			drain: -1
		},
		{
			spellCategory: 'manipulation',
			name: 'Levitate',
			isPhysical: true,
			isMental: false,
			isEnvironmental: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'manipulation',
			name: 'Light',
			isPhysical: false,
			isMental: false,
			isEnvironmental: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: -4
		},
		{
			spellCategory: 'manipulation',
			name: 'Magic Fingers',
			isPhysical: true,
			isMental: false,
			isEnvironmental: false,
			isLOS: true,
			isArea: false,
			isMana: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'manipulation',
			name: 'Mana Barrier',
			isPhysical: false,
			isMental: false,
			isEnvironmental: true,
			isLOS: true,
			isArea: true,
			isMana: true,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'manipulation',
			name: 'Physical Barrier',
			isPhysical: false,
			isMental: false,
			isEnvironmental: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: -1
		},
		{
			spellCategory: 'manipulation',
			name: 'Poltergeist',
			isPhysical: false,
			isMental: false,
			isEnvironmental: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: -2
		},
		{
			spellCategory: 'manipulation',
			name: 'Shadow',
			isPhysical: false,
			isMental: false,
			isEnvironmental: true,
			isLOS: true,
			isArea: true,
			isMana: false,
			duration: 'S',
			drain: -3
		}
	]
};

