export const PICK_METATYPE_OPTION = 'PICK_METATYPE_OPTION'
export const PICK_MAGIC_OR_RESONANCE_OPTION = 'PICK_MAGIC_OR_RESONANCE_OPTION'
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE'
export const SUBTRACT_ATTRIBUTE = 'SUBTRACT_ATTRIBUTE'