export const human = [
  {
    key: 'body',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'agility',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'reaction',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'strength',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'willpower',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'logic',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'intuition',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'charisma',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  {
    key: 'edge',
    minValue: 2,
    value: 0,
    maxValue: 7,
    isSpecialAttribute: true,
  },
  {
    key: 'essence',
    minValue: 6,
    value: 6,
  },
  {
    key: 'racial',
    value: 'none',
  },
]
export const elf = [
  { key: 'body',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'agility',
    minValue: 2,
    value: 0,
    maxValue: 7,
  },
  { key: 'reaction',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'strength',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'willpower',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'logic',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'intuition',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'charisma',
    minValue: 3, value: 0,
    maxValue: 8,
  },
  { key: 'edge',
    minValue: 1,
    value: 0,
    maxValue: 6,
    isSpecialAttribute: true,
  },
  { key: 'essence',
    minValue: 6, value: 6,
  },
  {
    key: 'racial',
    value: 'Low-Light Vision',
  },
]
export const dwarf = [
  { key: 'body',
    minValue: 3,
    value: 0,
    maxValue: 8,
  },
  { key: 'agility',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'reaction',
    minValue: 1,
    value: 0,
    maxValue: 5,
  },
  { key: 'strength',
    minValue: 3,
    value: 0,
    maxValue: 8,
  },
  { key: 'willpower',
    minValue: 2,
    value: 0,
    maxValue: 7,
  },
  { key: 'logic',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'intuition',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'charisma',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'edge',
    minValue: 1,
    value: 0,
    maxValue: 6,
    isSpecialAttribute: true,
  },
  { key: 'essence',
    minValue: 6, value: 6,
  },
  {
    key: 'racial',
    value: '+2 dice for pathogen and toxin resistance, +20% increased Lifestyle cost',
  },
]
export const ork = [
  { key: 'body',
    minValue: 4,
    value: 0,
    maxValue: 9,
  },
  { key: 'agility',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'reaction',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'strength',
    minValue: 3,
    value: 0,
    maxValue: 8,
  },
  { key: 'willpower',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'logic',
    minValue: 1,
    value: 0,
    maxValue: 5,
  },
  { key: 'intuition',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'charisma',
    minValue: 1,
    value: 0,
    maxValue: 5,
  },
  { key: 'edge',
    minValue: 1,
    value: 0,
    maxValue: 6,
    isSpecialAttribute: true,
  },
  { key: 'essence',
    minValue: 6, value: 6,
  },
  {
    key: 'racial',
    value: 'Low-Light Vision',
  },

]
export const troll = [
  { key: 'body',
    minValue: 5,
    value: 0,
    maxValue: 10,
  },
  { key: 'agility',
    minValue: 1,
    value: 0,
    maxValue: 5,
  },
  { key: 'reaction',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'strength',
    minValue: 5,
    value: 0,
    maxValue: 10,
  },
  { key: 'willpower',
    minValue: 1,
    value: 0,
    maxValue: 6,
  },
  { key: 'logic',
    minValue: 1,
    value: 0,
    maxValue: 5,
  },
  { key: 'intuition',
    minValue: 1,
    value: 0,
    maxValue: 5,
  },
  { key: 'charisma',
    minValue: 1,
    value: 0,
    maxValue: 4,
  },
  { key: 'edge',
    minValue: 1,
    value: 0,
    maxValue: 6,
    isSpecialAttribute: true,
  },
  { key: 'essence',
    minValue: 6, value: 6,
  },
  {
    key: 'racial',
    value: 'Thermographic Vision, +1 Reach, +1 Dermal Armor, +100% increased Lifestyle costs',
  },
]
