export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const ADD_WARE = 'ADD_WARE'
export const REMOVE_WARE = 'REMOVE_WARE'
export const ADD_WEAPON = 'ADD_WEAPON'
export const REMOVE_WEAPON = 'REMOVE_WEAPON'
export const SELECT_ACCESSORY = 'SELECT_ACCESSORY'
