export const positiveQualities = [
  {
    name: 'Ambidextrous',
    tags: [],
    karmaCost: 4,
    mods: [],
  },
  {
    name: 'Analytical Mind',
    tags: [],
    karmaCost: 5,
    mods: [],
  },
  {
    name: 'Aptitude',
    tags: [],
    karmaCost: 14,
    mods: [],
  },
  {
    name: 'Astral Chameleon',
    tags: [],
    karmaCost: 10,
    mods: [],
  },
  {
    name: 'Bilingual',
    tags: [],
    karmaCost: 5,
    mods: [],
  },
  {
    name: 'Blandness',
    tags: [],
    karmaCost: 8,
    mods: [],
  },
  {
    name: 'Catlike',
    tags: [],
    karmaCost: 7,
    mods: [],
  },
  {
    name: 'Codeslinger',
    tags: [],
    karmaCost: 10,
    mods: [],
  },
  {
    name: 'Double-Jointed',
    tags: [],
    karmaCost: 6,
    mods: [],
  },
  {
    name: 'Exceptional Attribute',
    tags: [],
    karmaCost: 14,
    mods: [],
  },
  {
    name: 'First Impression',
    tags: [],
    karmaCost: 11,
    mods: [],
  },
  {
    name: 'Focused Concentration',
    tags: [],
    karmaCost: 4,
    levels: 6,
    mods: [],
  },
  {
    name: 'Gearhead',
    tags: [],
    karmaCost: 11,
    mods: [],
  },
  {
    name: 'Guts',
    tags: [],
    karmaCost: 10,
    mods: [],
  },
  {
    name: 'High Pain Tolerance',
    tags: [],
    karmaCost: 7,
    levels: 3,
    mods: [],
  },
  {
    name: 'Home Ground',
    tags: [],
    karmaCost: 10,
    mods: [],
  },
  {
    name: 'Human Looking',
    tags: [],
    karmaCost: 6,
    mods: [],
  },
  {
    name: 'Indomitable',
    tags: [],
    karmaCost: 8,
    levels: 3,
    mods: [],
  },
  {
    name: 'Juryrigger',
    tags: [],
    karmaCost: 5,
    mods: [],
  },
  {
    name: 'Lucky',
    tags: [],
    karmaCost: 12,
    mods: [],
  },
  {
    name: 'Magical Resistance',
    tags: [],
    karmaCost: 6,
    levels: 4,
    mods: [],
  },
  {
    name: 'Mentor Spirit',
    tags: [],
    karmaCost: 5,
    mods: [],
  },
  {
    name: 'Natural Athlete',
    tags: [],
    karmaCost: 7,
    mods: [],
  },
  {
    name: 'Natural Hardening',
    tags: [],
    karmaCost: 10,
    mods: [],
  },
  {
    name: 'Natural Immunity (natural)',
    tags: [],
    karmaCost: 4,
    mods: [],
  },
  {
    name: 'Natural Immunity (synthentic)',
    tags: [],
    karmaCost: 10,
    mods: [],
  },
  {
    name: 'Photographic Memory',
    tags: [],
    karmaCost: 6,
    mods: [],
  },
  {
    name: 'Quick Healer',
    tags: [],
    karmaCost: 3,
    mods: [],
  },
  {
    name: 'Resistance to Pathogens / Toxins (choose one)',
    tags: [],
    karmaCost: 4,
    mods: [],
  },
  {
    name: 'Resistance to Pathogens / Toxins (both)',
    tags: [],
    karmaCost: 8,
    mods: [],
  },
  {
    name: 'Spirit Affinity',
    tags: [],
    karmaCost: 7,
    mods: [],
  },
  {
    name: 'Toughness',
    tags: [],
    karmaCost: 9,
    mods: [],
  },
  {
    name: 'Will to Live',
    tags: [],
    karmaCost: 3,
    levels: 3,
    mods: [],
  },
]

export const negativeQualities = [
  {
    name: 'Addiction (Mild)',
    tags: [],
    karmaCost:-4,
    mods: [],
  },
  {
    name: 'Addiction (Moderate)',
    tags: [],
    karmaCost:-9,
    mods: [],
  },
  {
    name: 'Addiction (Severe)',
    tags: [],
    karmaCost:-20,
    mods: [],
  },
  {
    name: 'Addiction (Burnout)',
    tags: [],
    karmaCost:-24,
    mods: [],
  },
  {
    name: 'Allergy (Common Mild)',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'Allergy (Common Moderate)',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Allergy (Common Severe)',
    tags: [],
    karmaCost:-15,
    mods: [],
  },
  {
    name: 'Allergy (Common Extreme)',
    tags: [],
    karmaCost:-20,
    mods: [],
  },{
    name: 'Allergy (Uncommon Mild)',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Allergy (Uncommon Moderate)',
    tags: [],
    karmaCost:-15,
    mods: [],
  },
  {
    name: 'Allergy (Uncommon Severe)',
    tags: [],
    karmaCost:-20,
    mods: [],
  },
  {
    name: 'Allergy (Uncommon Extreme)',
    tags: [],
    karmaCost:-25,
    mods: [],
  },
  {
    name: 'Astral Beacon',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Bad Luck',
    tags: [],
    karmaCost:-12,
    mods: [],
  },
  {
    name: 'Bad Rep',
    tags: [],
    karmaCost:-7,
    mods: [],
  },
  {
    name: 'Code of Honor',
    tags: [],
    karmaCost:-15,
    mods: [],
  },
  {
    name: 'Codeblock',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Combat Paralysis',
    tags: [],
    karmaCost:-12,
    mods: [],
  },
  {
    name: 'Dependents',
    tags: [],
    karmaCost:-3,
    levels:3,
    mods: [],
  },
  {
    name: 'Distinctive Lifestyle',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'Elf Poser',
    tags: [],
    karmaCost:-6,
    mods: [],
  },
  {
    name: 'Gremlins',
    tags: [],
    karmaCost:-4,
    levels:4,
    mods: [],
  },
  {
    name: 'Incompetant',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'Insomnia (bad)',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Insomnia (real bad)',
    tags: [],
    karmaCost:-15,
    mods: [],
  },
  {
    name: 'Loss of Confidence',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Low Pain Tolerance',
    tags: [],
    karmaCost:-9,
    mods: [],
  },
  {
    name: 'Ork Poser',
    tags: [],
    karmaCost:-6,
    mods: [],
  },
  {
    name: 'Prejudiced (Common Biased)',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'Prejudiced (Common Outspoken)',
    tags: [],
    karmaCost:-7,
    mods: [],
  },
  {
    name: 'Prejudiced (Common Radical)',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Prejudiced (Specific Biased)',
    tags: [],
    karmaCost:-3,
    mods: [],
  },
  {
    name: 'Prejudiced (Specific Outspoken)',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'Prejudiced (Specific Radical)',
    tags: [],
    karmaCost:-8,
    mods: [],
  },
  {
    name: 'Scorched',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Sensitive System',
    tags: [],
    karmaCost:-12,
    mods: [],
  },
  {
    name: 'Simsense Vertigo',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'National SIN',
    tags: [],
    karmaCost:-5,
    mods: [],
  },
  {
    name: 'Criminal SIN',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
  {
    name: 'Corporate Limited SIN',
    tags: [],
    karmaCost:-15,
    mods: [],
  },
  {
    name: 'Corporate SIN',
    tags: [],
    karmaCost:-25,
    mods: [],
  },
  {
    name: 'Social Stress',
    tags: [],
    karmaCost:-8,
    mods: [],
  },
  {
    name: 'Sprit Bane',
    tags: [],
    karmaCost:-7,
    mods: [],
  },
  {
    name: 'Uncouth',
    tags: [],
    karmaCost:-14,
    mods: [],
  },
  {
    name: 'Uneducated',
    tags: [],
    karmaCost:-8,
    mods: [],
  },
  {
    name: 'Unsteady Hands',
    tags: [],
    karmaCost:-7,
    mods: [],
  },
  {
    name: 'Weak Immune System',
    tags: [],
    karmaCost:-10,
    mods: [],
  },
]
