import { skillMap } from "./skills"

export default [
  {
    name: 'Acting',
    points: 0,
    skills: [skillMap.con,
      skillMap.impersonation,
      skillMap.performance],
  },
  {
    name: 'Athletics',
    points: 0,
    skills: [skillMap.gymnastics,
      skillMap.running,
      skillMap.swimming],
  },
  {
    name: 'Biotech',
    points: 0,
    skills: [skillMap.cybertechnology,
      skillMap.firstAid,
      skillMap.medicine],
  },
  {
    name: 'Close Combat',
    points: 0,
    skills: [skillMap.blades,
      skillMap.clubs,
      skillMap.unarmedCombat],
  },
  {
    name: 'Conjuring',
    points: 0,
    skills: [skillMap.banishing,
      skillMap.binding,
      skillMap.summoning],
  },
  {
    name: 'Cracking',
    points: 0,
    skills: [skillMap.cybercombat,
      skillMap.electronicWarfare,
      skillMap.hacking],
  },
  {
    name: 'Electronics',
    points: 0,
    skills: [skillMap.computer,
      skillMap.hardware,
      skillMap.software],
  },
  {
    name: 'Enchanting',
    points: 0,
    skills: [skillMap.alchemy,
      skillMap.artificing,
      skillMap.disenchanting],
  },
  {
    name: 'Engineering',
    points: 0,
    skills: [skillMap.aeronauticsMechanics,
      skillMap.automotiveMechanics,
      skillMap.industrialMechanics,
      skillMap.nauticalMechanics],
  },
  {
    name: 'Firearms',
    points: 0,
    skills: [skillMap.automatics,
      skillMap.longarms,
      skillMap.pistols],
  },
  {
    name: 'Influence',
    points: 0,
    skills: [skillMap.etiquette,
      skillMap.leadership,
      skillMap.negotiation],
  },
  {
    name: 'Outdoors',
    points: 0,
    skills: [skillMap.navigation,
      skillMap.survival,
      skillMap.tracking],
  },
  {
    name: 'Sorcery',
    points: 0,
    skills: [skillMap.counterspelling,
      skillMap.ritualSpellcasting,
      skillMap.spellcasting],
  },
  {
    name: 'Stealth',
    points: 0,
    skills: [skillMap.disguise,
      skillMap.palming,
      skillMap.sneaking],
  },
  {
    name: 'Tasking',
    points: 0,
    skills: [skillMap.compiling,
      skillMap.decompiling,
      skillMap.registering],
  },
]
