import * as spellCategories from './spellCategories'

export default [

  {
    spellCategory: spellCategories.COMBAT,
    isElemental: true,
    isDirect: false,
    name: 'Acid Stream',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: false,
    isPhysicalDamage: true,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: true,
    isDirect: false,
    name: 'Toxic Wave',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: false,
    isPhysicalDamage: true,
    drain: -1,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: false,
    name: 'Punch',
    tags: [],
    isLOS: false,
    isArea: false,
    isMana: false,
    isPhysicalDamage: false,
    drain: -6,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: false,
    name: 'Clout',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: false,
    isPhysicalDamage: false,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: false,
    name: 'Blast',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: false,
    isPhysicalDamage: false,
    drain: 0,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'DeathTouch',
    tags: [],
    isLOS: false,
    isArea: false,
    isMana: true,
    isPhysicalDamage: true,
    drain: -6,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Manabolt',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: true,
    isPhysicalDamage: true,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Manaball',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: true,
    isPhysicalDamage: true,
    drain: 0,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: true,
    isDirect: false,
    name: 'Flamethrower',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: false,
    isPhysicalDamage: true,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: true,
    isDirect: false,
    name: 'Fireball',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: false,
    isPhysicalDamage: true,
    drain: -1,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: true,
    isDirect: false,
    name: 'Lightning Bolt',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: false,
    isPhysicalDamage: true,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: true,
    isDirect: false,
    name: 'Ball Lightning',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: false,
    isPhysicalDamage: true,
    drain: -1,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Shatter',
    tags: [],
    isLOS: false,
    isArea: false,
    isMana: false,
    isPhysicalDamage: true,
    drain: -6,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Powerbolt',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: false,
    isPhysicalDamage: true,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Powerball',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: false,
    isPhysicalDamage: true,
    drain: 0,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Knockout',
    tags: [],
    isLOS: false,
    isArea: false,
    isMana: true,
    isPhysicalDamage: false,
    drain: -6,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Stunbolt',
    tags: [],
    isLOS: true,
    isArea: false,
    isMana: true,
    isPhysicalDamage: false,
    drain: -3,
    duration: 'I',
  },
  {
    spellCategory: spellCategories.COMBAT,
    isElemental: false,
    isDirect: true,
    name: 'Stunball',
    tags: [],
    isLOS: true,
    isArea: true,
    isMana: true,
    isPhysicalDamage: false,
    drain: 0,
    duration: 'I',
  },

  {
    spellCategory: spellCategories.DETECTION,
    name: 'Analyze Device',
    tags: [],
    isActive: true,
    isDirectional: true,
    isMana: false,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Analyze Magic',
    tags: [],
    isActive: true,
    isDirectional: true,
    isMana: false,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Analyze Truth',
    tags: [],
    isActive: true,
    isDirectional: true,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Clairaudience',
    tags: [],
    isActive: false,
    isDirectional: true,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Clairvoyance',
    tags: [],
    isActive: false,
    isDirectional: true,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Combat Sense',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: true,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect Enemies',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: true,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect Enemies, Extended',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: true,
    isPsychic: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect Individual',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: true,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect Life',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: true,
    isPsychic: false,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect [Life Form]',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: true,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect [Life Form], Extended',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: true,
    isPsychic: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect Magic',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: true,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect Magic, Extended',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: true,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Detect [Object]',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: false,
    isLOS: false,
    isArea: true,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Mindlink',
    tags: [],
    isActive: true,
    isDirectional: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: true,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.DETECTION,
    name: 'Mind Probe',
    tags: [],
    isActive: true,
    isDirectional: true,
    isMana: true,
    isLOS: false,
    isArea: false,
    isExtendedArea: false,
    isPsychic: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Antidote',
    tags: [],
    isEssence: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'P',
    drain: -3,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Cure Disease',
    tags: [],
    isEssence: true,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'P',
    drain: -4,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Decrease [Attribute]',
    tags: [],
    isEssence: true,
    isMana: false,
    isLOS: false,
    isArea: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Detox',
    tags: [],
    isEssence: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'P',
    drain: -6,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Heal',
    tags: [],
    isEssence: true,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'P',
    drain: -4,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Increase [Attribute]',
    tags: [],
    isEssence: true,
    isMana: false,
    isLOS: false,
    isArea: false,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Increase Reflexes',
    tags: [],
    isEssence: true,
    isMana: false,
    isLOS: false,
    isArea: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Oxygenate',
    tags: [],
    isEssence: false,
    isMana: false,
    isLOS: false,
    isArea: false,
    duration: 'S',
    drain: -5,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Prophylaxis',
    tags: [],
    isEssence: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'S',
    drain: -4,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Resist Pain',
    tags: [],
    isEssence: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'P',
    drain: -6,
  },
  {
    spellCategory: spellCategories.HEALTH,
    name: 'Stabilize',
    tags: [],
    isEssence: false,
    isMana: true,
    isLOS: false,
    isArea: false,
    duration: 'P',
    drain: -4,
  },

  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Agony',
    tags: [],
    isRealistic: true,
    isMultisense: false,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: -4,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Mass Agony',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Bugs',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Swarm',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Confusion',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Mass Confusion',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Chaos',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Chaotic World',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Entertainment',
    tags: [],
    isRealistic: false,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -3,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Trid Entertainment',
    tags: [],
    isRealistic: false,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Invisibility',
    tags: [],
    isRealistic: true,
    isMultisense: false,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Improved Invisibility',
    tags: [],
    isRealistic: true,
    isMultisense: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Mask',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: false,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Physical Mask',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: false,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Phantasm',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Trid Phantasm',
    tags: [],
    isRealistic: true,
    isMultisense: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: 0,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Hush',
    tags: [],
    isRealistic: true,
    isMultisense: false,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Silence',
    tags: [],
    isRealistic: true,
    isMultisense: false,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.ILLUSION,
    name: 'Stealth',
    tags: [],
    isRealistic: true,
    isMultisense: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -2,
  },

  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Armor',
    tags: [],
    isPhysical: true,
    isMental: false,
    isEnvironmental: false,
    isDamaging: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Control Actions',
    tags: [],
    isPhysical: false,
    isMental: true,
    isEnvironmental: false,
    isDamaging: false,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Mob Control',
    tags: [],
    isPhysical: false,
    isMental: true,
    isEnvironmental: false,
    isDamaging: false,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: 1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Control Thoughts',
    tags: [],
    isPhysical: false,
    isMental: true,
    isEnvironmental: false,
    isDamaging: false,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'S',
    drain: 1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Mob Mind',
    tags: [],
    isPhysical: false,
    isMental: true,
    isEnvironmental: false,
    isDamaging: false,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: 1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'fling',
    tags: [],
    isPhysical: true,
    isMental: false,
    isEnvironmental: false,
    isDamaging: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'I',
    drain: -2,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Ice Sheet',
    tags: [],
    isPhysical: false,
    isMental: false,
    isEnvironmental: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'I',
    drain: 0,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Ignite',
    tags: [],
    isPhysical: true,
    isMental: false,
    isEnvironmental: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'P',
    drain: -1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Influence',
    tags: [],
    isPhysical: false,
    isMental: true,
    isEnvironmental: false,
    isLOS: true,
    isArea: false,
    isMana: true,
    duration: 'P',
    drain: -1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Levitate',
    tags: [],
    isPhysical: true,
    isMental: false,
    isEnvironmental: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Light',
    tags: [],
    isPhysical: false,
    isMental: false,
    isEnvironmental: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: -4,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Magic Fingers',
    tags: [],
    isPhysical: true,
    isMental: false,
    isEnvironmental: false,
    isLOS: true,
    isArea: false,
    isMana: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Mana Barrier',
    tags: [],
    isPhysical: false,
    isMental: false,
    isEnvironmental: true,
    isLOS: true,
    isArea: true,
    isMana: true,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Physical Barrier',
    tags: [],
    isPhysical: false,
    isMental: false,
    isEnvironmental: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: -1,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Poltergeist',
    tags: [],
    isPhysical: false,
    isMental: false,
    isEnvironmental: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: -2,
  },
  {
    spellCategory: spellCategories.MANIPULATION,
    name: 'Shadow',
    tags: [],
    isPhysical: false,
    isMental: false,
    isEnvironmental: true,
    isLOS: true,
    isArea: true,
    isMana: false,
    duration: 'S',
    drain: -3,
  },
]
