// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/src/reasonReact.js");

var component = ReasonReact.statelessComponent("ArmorItem");

function make(item, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, item.name);
    });
  return newrecord;
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.item, /* array */[]);
      }));

exports.component   = component;
exports.make        = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
